# Generated by Django 5.2.7 on 2025-10-27 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('capital', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('currency_code', models.CharField(max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_gdp', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('flag_url', models.URLField(blank=True, null=True)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefreshStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_refreshed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_countries', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'refresh_status',
            },
        ),
    ]
